### ISSUE TITLE
Sort classes inside 'clsx'/'classNames' functions

### ISSUE THREAD

**Issue by kripod** [Acidic9/prettier-plugin-tailwind#11]
First of all, thank you for the great work on this plugin!

Considering migration from [prettier-tailwind](https://github.com/marcosvega91/prettier-tailwind/), I think that class string sorting inside [`clsx`](https://github.com/JedWatson/classnames) and [`classNames`](https://github.com/JedWatson/classnames) calls would greatly improve the authoring experience.

**Comment by Acidic9** [comment]
I'll look into adding a prettier option which allows you to specify function names which will sort the string in the arguments.

I didn't think about adding this but it's definitely a great feature - hopefully will be implemented soon.

**Comment by kripod** [comment]
That’s a great idea for the implementation. I think it should have an array of reasonable default values (e.g. `["clsx", "classNames", "cc"]`).

**Comment by Acidic9** [comment]
Added new option `twJsxClassAttributes` with a default value of `class,className,tw` in version `2.2.3` which sorts the strings in the arguments.

Eg:
```jsx
clsx('w-full container') // becomes 'container w-full'
clsx`w-full container` // becomes `container w-full`
```

I hope this is what you were requesting!
