### ISSUE TITLE
Does not compatible with Prettier 2.3.0

### ISSUE THREAD

**Issue by nghieptiki** [Acidic9/prettier-plugin-tailwind#31]
**Describe the bug**
When upgrading to the latest Prettier(2.3.0)
```
"could not find a copy of prettier to link in <>/node_modules/prettier-plugin-tailwind/node_modules"
```

**To Reproduce**
```sh
$ yarn add -D prettier
```

**Versions:**
 - prettier-plugin-tailwind version: 2.2.10
 - Operating system: macOS
 - NPM/Yarn version: 1.22.10

**Comment by Acidic9** [comment]
Please see https://github.com/Acidic9/prettier-plugin-tailwind/issues/33
