### ISSUE TITLE
Tailwind CSS v2 support

### ISSUE THREAD

**Issue by anantakrishna** [Acidic9/prettier-plugin-tailwind#33]
According to the dependencies of this package, it relies on Tailwind CSS v1.x

It's good to have v2 support.

**Comment by j0hnm4r5** [comment]
This is related to https://github.com/Acidic9/prettier-plugin-tailwind/pull/30

**Comment by Acidic9** [comment]
I've published v2.2.12 which should resolve this issue. Let me know if you have any other problems with it.
