### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by erianvc** [Acidic9/prettier-plugin-tailwind#4]
I would like this plugin to have support for Svelte files
The Svelte files are very similar to HTML

**Comment by Acidic9** [comment]
Will implement it if I get time, but feel free to create a PR if you want to give it a shot.

**Comment by Acidic9** [comment]
I just fell in love with svelte this week..!

Will most likely give svelte support a go so I can use it in my own projects too

**Comment by erianvc** [comment]
I'm very happy with that decision, it's a good framework

**Comment by netaisllc** [comment]
It's tempting to forgo TailwindCSS in favor of Svelte's own handling of scoped CSS classes, but I'm keeping an open mind and trying to go full TW on a project.  This plugin would be such a help to keep Svelte components understandable! Props to you.

**Comment by Acidic9** [comment]
Thanks! @netaisllc just out of curiousity, are you using tailwind as classes in your elements, or are you going the `@apply` only route? Personally I have been using `@apply` to save the resulting css size but I'm not sure which approach is better.. I just feel like `@apply` is cleaner.

**Comment by erianvc** [comment]
@Acidic9 I select the elements within the component and apply the styles with the `@apply` directive.
[See an example of my portfolio's card](https://github.com/erianvc/erianvc.dev/blob/dev/src/components/Card.svelte)

**Comment by netaisllc** [comment]
@Acidic9 I'm old-school, so I'm applying _all_ the TW classes to the markup in the component. 

I take your point about `@apply` feeling cleaner -- haha, the huge class list is the main reason I'm searching for a class name sorter tbh - but the `apply` technique to me feels like it's going against one of TW's main value props (no pun intended): _It's brutally clear from the markup alone what styles are in play_. (And that's coming from an old CSS hand like me).

For my stuff, the future benefit of that for refactoring/elaboration is worth.  Also, haven't seen much of an issue with CSS size on my enterprise scale projects prob b/c Svelte is so small in an of itself.

**Comment by Acidic9** [comment]
Added support in version 2.2.0 !   🎉

**Comment by nickyhajal** [comment]
Just wanted to check in - is Svelte currently supported? I tried using this, but it seemed to go extremely slow/hang on a Svelte project, so I'm not sure if as stated in #16, Svelte is not currently supported.


> Personally I have been using `@apply` to save the resulting css size but I'm not sure which approach is better.. I just feel like `@apply` is cleaner.

Off-topic, but curious: how does using `@apply` result in less CSS size?

Thanks!
