### ISSUE TITLE
ESlint support ?

### ISSUE THREAD

**Issue by kissu** [Acidic9/prettier-plugin-tailwind#7]
Hi !
I do actually use VScode's `Headwind` extension to format my classes.

I didn't found a way of doing this with basically any code editor/IDE. I was wondering if it's somehow planned to support formatting through ESlint, that way: my colleagues will have auto-formatted classes whatever the editor.

**Comment by Acidic9** [comment]
Hi 👋

I'm sorry to hear that it doesn't work with the editors you/your colleges use. 

An eslint plugin wouldn't be too tricky to get created, as the code for sorting tailwind classes is it's own package under [tailwind-classes-sorter](https://www.npmjs.com/package/tailwind-classes-sorter) on NPM.
I don't have a lot of time to work on a new project like that currently, but you or your team are welcome to give it a go, it shouldn't be too tricky. 

For now the only thing I can suggest is that they can use this plugin if they use prettier as a cli command, perhaps even as a git hook setup using something like [husky](https://github.com/typicode/husky).

**Comment by kissu** [comment]
Alright, will maybe give a try !
Husky is awesome indeed, already formatting some JSON and stuff with it. 👍🏻
